### ISSUE TITLE
Scrollbars are visible on chrome

### ISSUE THREAD

**Issue by YanWittmann** [Skyball2000/launch-anything#14]
```css
.hide-scrollbar::-webkit-scrollbar {
    display: none;
}
```
adding this should fix it
